import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Wrap it with the top level sessionprovider component */}
        <Providers>
          {/**Here comes the Other providers like the theme providers */}
          {/*Then comes the Recoilroot in order after all these */}
          {children}
        </Providers>
      </body>
    </html>
  );
}
